name = "FETI"
uuid = "3e09b334-b32d-4a6e-b445-7ae852035792"
authors = ["Jared Frazier <cscidev001@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
